### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by manoelcfeliciano** [GeoffZhu/vue-event-calendar#1]
Really nice plugin. But there is a problem with the date format for events.

For example:
When I put an event at the date: '2017/2/16' it does show up

But when I change to '2017/02/16' it does not.

Should I send a pr?

**Comment by GeoffZhu** [comment]
it's a bug, your can send a pr, thanks

**Comment by GeoffZhu** [comment]
Already fix it, update your npm package
