### ISSUE TITLE
Change the curYearMonth

### ISSUE THREAD

**Issue by andrevildozo** [GeoffZhu/vue-event-calendar#10]
Hi, guys how can i change in the calendar the curYearMonth for the MONTH but not de number but the name Example the calendar show <  03/2017 > A like change < APRIL/2017 > our  < APRIL >. And 
In which file i do this change.

Thank's

**Comment by GeoffZhu** [comment]
Just change one function in file [cal-panel.vue](https://github.com/GeoffZhu/vue-event-calendar/blob/master/src/components/cal-panel.vue#L86),  maybe like this:
```javascript
curYearMonth () {
  let mouthArray = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
  return `${mouthArray[this.calendar.params.curMonth]}/${this.calendar.params.curYear}`
}
```


Done. @andrevildozo

**Comment by renanol** [comment]
@GeoffZhu Could have a full month option. How @andrevildozo described.

**Comment by GeoffZhu** [comment]
Hah, My English is not really good，thank you for explaining @renanol.  Back to the issue itself, I do not intend to add this option. The original intention of make this component  is simple. Too much configuration, maybe causing trouble. You can change Source code meet you needs.

**Comment by renanol** [comment]
haha no problem, You're right @GeoffZhu, may cause problems. I can change source. 
Thank you!
