### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by renanol** [GeoffZhu/vue-event-calendar#11]
Hi! My date format is 2017-02-23, but you comparable with    `${dateObj.getFullYear()}/${dateObj.getMonth()+1}/${dateObj.getDate()` to mark today style, What is better solution ? Convert '-' to '/' in your component, or in my api? I prefer in your plugin, it become generic.

**Comment by GeoffZhu** [comment]
thanks，In this component, date format based on ''yyyy/MM/dd'', So there have many ```split('/')``` in my code.
#### Change date format which user sees 
In file i18n.js. change 'format' and 'fullFormat' to 'yyyy-MM' 'yyyy-MM-dd'

#### Raw events Object date format is 'yyyy-MM-dd'
 In Vue.js, is so easy to change it, just like this
``` javascript
<vue-event-calendar :events="computedEvents"></vue-event-calendar>

<script>
export default {
  name: 'app',
  data () {
    return {
      demoEvents: [{
        date: '2016-12-15',
        title: 'eat',
        desc: 'longlonglong description'
      },{
        date: '2017-02-12',
        title: 'this is a title'
      }]
    }
  },
  computed: {
    computedEvents () {
      // JSON.parse(JSON.stringify(this.demoEvents)) cut off object reference
      return JSON.parse(JSON.stringify(this.demoEvents)).map((eventItem) => {
        eventItem.date = eventItem.date.split('-').join('/')
        return eventItem
      })
    }
  }
}
</script>
```

**Comment by renanol** [comment]
Great solution! Thank you. I needed implement this solution in `created`, because I use vue routes and don't call computed in change url.

**Comment by GeoffZhu** [comment]
@renanol 😄， It' OK , when data change,  Vue.js will call computed. In fact, we don't need to pay attention to routes, concerned about the original data just fine. My poor English, Hope my expression, you can understand.

**Comment by renanol** [comment]
@GeoffZhu thank you, I get it! You help me a lot =).
