### ISSUE TITLE
Listen to a month change event

### ISSUE THREAD

**Issue by shigg1120** [GeoffZhu/vue-event-calendar#16]
Thanks for the cool calendar library.

I was wandering if there is a way to listen to something like a month change event, so I can perform an ajax request to get all the events for the month

**Comment by GeoffZhu** [comment]
ok,  I will add this for you, this week.

**Comment by shigg1120** [comment]
Thank you so much!!

**Comment by GeoffZhu** [comment]
I add two event in version 1.3.2, also change the doc  para #Events @shigg1120 
```
@day-changed="handleDayChanged"
 @month-changed="handleMonthChanged"
```

**Comment by shigg1120** [comment]
Thanks man @GeoffZhu

**Comment by rajjanorkar** [comment]
this handleMonthChanged does not work
