### ISSUE TITLE
can you please add lang "ko", too?

### ISSUE THREAD

**Issue by gabrieljo** [GeoffZhu/vue-event-calendar#19]
Thanks for your calendar, I am using this and it is quite awsome.
I need lang "ko"
please add this.

**Comment by GeoffZhu** [comment]
use google translate to ko,  In this [commit](https://github.com/GeoffZhu/vue-event-calendar/commit/1820c176be50f754f597d498b8f14d8e58d54a13 ).  Is it right? If not , You can send a PR . @gabrieljo

**Comment by gabrieljo** [comment]
it is correct. thanks a lot :)

have good day

2017-06-06 15:34 GMT+12:00 Wis <notifications@github.com>:

**Comment by GeoffZhu** [comment]
Update npm package to 1.3.2, can use ko. @gabrieljo
