### ISSUE TITLE
事件详情面板能放到日期面板里吗？

### ISSUE THREAD

**Issue by superbowen** [GeoffZhu/vue-event-calendar#21]
比如7号有一个event对象，在数字7的旁边显示一个tooltip（显示event.title）

**Comment by GeoffZhu** [comment]
因为我自己工作的业务中也在用这个组件，所以多余的功能不太能增加，你可以复制一份源码，然后自己改一下，抱歉

**Comment by superbowen** [comment]
好吧，我也是想偷个懒，看来还是得自己动手了
