### ISSUE TITLE
dayList:"(error during evaluation)" error

### ISSUE THREAD

**Issue by gabrieljo** [GeoffZhu/vue-event-calendar#22]
Hey mate, 

I faced an error. I am using vuex and, as for the events props I put data using getter from computed not model like,

<vue-event-calendar :events="events"></vue-event-calendar>
...
computed: {
            events(){
                return this.$store.getters.events;
            }
        },

when the calender render, it shows me an error "vue.esm.js?65d7:523 TypeError: Cannot read property 'split' of undefined"

I was tracing using vue-tools, I found the problem. In the "CalPanel", the day list cannot make days, it said, "dayList:"(error during evaluation)"" 

is there a any way to solve this problem?

cheers,

**Comment by GeoffZhu** [comment]
Check the events (this.$store.getters.events) Array,.
 Empty Object or Incorrect event format in it  at some point

 both empty Object and Incorrect event format can lead to this error

I add a validator for this error , in 1.3.3,

**Comment by gabrieljo** [comment]
I found the problem, when I match column name with your data model. it works properly.

thanks,
