### ISSUE TITLE
How do i scope the styles for this package?

### ISSUE THREAD

**Issue by scottgrayson** [GeoffZhu/vue-event-calendar#23]
Importing the css in main.js applies this style.

`h3,p{margin:0;padding:0}`

I do not want this applied globally.

**Comment by fbove** [comment]
What do you think about [this PR](https://github.com/GeoffZhu/vue-event-calendar/pull/25) ?

**Comment by scottgrayson** [comment]
@fbove that will fix my problem

**Comment by GeoffZhu** [comment]
1.3.4 fix it, thanks @fbove
