### ISSUE TITLE
Use DateTime instead of Date ?

### ISSUE THREAD

**Issue by fbove** [GeoffZhu/vue-event-calendar#26]
It could be great to set DateTime instead of just a Date for events.
In my case, there are events happening on the same day.

**Comment by GeoffZhu** [comment]
Custom template can meet this needs, 
![image](https://user-images.githubusercontent.com/10768286/26960630-39b50a34-4d0b-11e7-9391-c759edebf872.png)
,  add a var time in event obj.

**Comment by fbove** [comment]
I've done it the way you proposed:
```
vue-event-calendar(:events='demoEvents')
  template(scope='props')
    .event-item(v-for='(event, index) in props.showEvents')
      .wrapper
        h3.title {{index+1}}. {{event.title}}
          p.time {{event.date}} {{event.time}}
          p.desc {{event.desc}}
```
How ever it could be nice if the default template shows DateTimes. For example this event...
```
{
  date: '2017-06-22 01:02:03',
  title: 'Foo',
  desc: 'longlonglong description',
}
```
... would output 2017-06-22 01:02:03 on default template, instead of just 2017-06-22.

Thanks for feedback :)

**Comment by GeoffZhu** [comment]
In the source, use so many ```event.date.split('/')```, to process date. If use DateTime instead of Date, I think I should rewrite this project. Maybe in Vue3, I will do this. :) @fbove
