### ISSUE TITLE
how to resolve too many tasks in the same day

### ISSUE THREAD

**Issue by chouchou723** [GeoffZhu/vue-event-calendar#28]
how to resolve too many tasks in the same day?
like one day,i have ten tasks ,but if i use overflow,
the scroll-bar is too urgly

**Comment by GeoffZhu** [comment]
rewrite css  in dist folder  is the best way. For example, I change the layout like this,  in my project
![image](https://user-images.githubusercontent.com/10768286/27120078-d1e3da12-5114-11e7-9efa-1ec0a18ca1b8.png)
