### ISSUE TITLE
自定义模板的事件绑定无效

### ISSUE THREAD

**Issue by chouchou723** [GeoffZhu/vue-event-calendar#30]
<vue-event-calendar :events="demoEvents"  @day-changed="handleDayChanged" @month-changed="handleMonthChanged">
            <template scope="props" class="event-item1">
                <div v-for="(event, index) in props.showEvents" class="event-item"  @click.native="pop(event)">
                    <div @click.native="pop(event)">
                                   {{event.title}}
                       <\/div>
               <\/div>
              <\/template>
<\/vue-event-calendar>

不知道为什么，自定义内容里写点击事件无效，不管写在v-for的位置 还是写在里面的位置，这个到底应该写在哪？

**Comment by GeoffZhu** [comment]
去掉.native
