### ISSUE TITLE
这个组件在android5.0的系统 有兼容性问题呀 导致引入的项目页面都打不开了

### ISSUE THREAD

**Issue by 617450941** [GeoffZhu/vue-event-calendar#32]
这个组件在android5.0的系统 有兼容性问题呀 导致引入这组件的项目页面都打不开了 android6.0以上的系统没这问题  我的环境是webpack + vue2.1.10  然后还有个问题 这个组件怎么局部引入

**Comment by GeoffZhu** [comment]
报什么错误，我看看能不能修复，在我的安卓(底层版本4.4.2)手机上没有问题

**Comment by 617450941** [comment]
提示 这个 访问你的demo页面也一样 报这个错误Uncaught TypeError: undefined is not a function", source: http://geoffzhu.cn/vue-event-calendar/dist/build.js

**Comment by 617450941** [comment]
在安卓5.1系统的环境下报的错误 我try catch才看的到这个错误的 不用try catch的话整个vue框架会因为这个问题无法执行下去导致白屏无法渲染页面   错误提示如下： [Vue warn]: Unknown custom element: <vue-event-calendar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

            found in

**Comment by 617450941** [comment]
所以我想问下有没局部引入的方法 我看下能不能解决这问题

**Comment by GeoffZhu** [comment]
局部引入的话，需要改动的地方比较多，入口是src/vue-event-calendar

**Comment by GeoffZhu** [comment]
我手里没有安卓5.1的设备，你可以将源码下载下来，然后Vue.use源码中src/index.js，未压缩的代码会有详细的错误提示，具体是哪里undefined，然后尝试修一下

**Comment by 617450941** [comment]
index.js  58行 object.assign 有兼容性问题 导致程序无法执行

**Comment by 617450941** [comment]
index.js 58行 object.assign 有兼容性问题 导致程序无法执行 Object.assign(DEFAULT_OPTION, options)  改成JSON.parse(JSON.stringify(DEFAULT_OPTION)) 这次就解决问题了 这个深拷贝方法 有些安卓设备不支持

**Comment by 617450941** [comment]
大神什么时候能解决这个bug推送到npm上  我项目急用

**Comment by GeoffZhu** [comment]
这个你可以自己解决的，在vue初始化之前，引入object.assign的[Polyfill](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

```javascript
if (typeof Object.assign != 'function') {
  Object.assign = function(target) {
    'use strict';
    if (target == null) {
      throw new TypeError('Cannot convert undefined or null to object');
    }

    target = Object(target);
    for (var index = 1; index < arguments.length; index++) {
      var source = arguments[index];
      if (source != null) {
        for (var key in source) {
          if (Object.prototype.hasOwnProperty.call(source, key)) {
            target[key] = source[key];
          }
        }
      }
    }
    return target;
  };
}
```

**Comment by 617450941** [comment]
这个代码放到哪 我小白不懂 能不能详细点 谢谢

**Comment by GeoffZhu** [comment]
单独放在一个js文件里叫assign-ployfill.js

在import vueEventCalendar from 'vue-event-calendar'之前的任意位置引入上面的这个js

**Comment by 617450941** [comment]
哦好的 谢谢

**Comment by 617450941** [comment]
貌似这样引入还是解决不了问题 我的环境是vue cli的

**Comment by GeoffZhu** [comment]
还可以在页面中的加载vue相关js的script标签之前加一个script标签，然后放入上面的那段js代码。
目的是，让Object.assign变成一个可用的函数。

如果还是不行，剩下的我就不能帮助你了，你需要补一下低版本浏览器polyfill和shim相关基础知识，就能解决这个问题了。

**Comment by 617450941** [comment]
最后还是引入babel-polyfill这个库解决了....
