### ISSUE TITLE
异步获取数据怎么默认显示当天事件

### ISSUE THREAD

**Issue by slimeball** [GeoffZhu/vue-event-calendar#34]
我想进入的时候默认显示当天事件，尝试操作vue-event-calendar.vue组件里的selectedDayEvents，不过还没获取数据之前处理方法就执行完了，把事件全部都显示出来了。然后尝试在vue-event-calendar.vue组件里异步success拼接数据后执行handleChangeCurDay，依然是数据没渲染就执行完了，还是把事件都显示出来了。有什么方法可以默认显示当天事件吗？

**Comment by GeoffZhu** [comment]
this.$EventCalendar.toDate('2016/11/12'), 尝试下这种方式

**Comment by slimeball** [comment]
放在哪里，我放在异步体内没效果，在数据渲染前就执行完了

**Comment by GeoffZhu** [comment]
已经解决了，应该是因为当天没有event，所以toDate不成功，我从新传了npm, 更新到1.4.4, 应该就生效了
 @slimeball

**Comment by slimeball** [comment]
```
data(){
 return {
      curday:`${new Date().getFullYear()}/${new Date().getMonth() + 1}/${new Date().getDate()}`,
      demoEvents: []
  }
}
```
我把你的整个组件都扔到项目里定制，除了这个其他的运作都正常。。。感觉这个问题好顽固。。
我用的本地json，有考虑到当天没事件，有修改到当天。打断点是数据还没出来就执行了处理的方法，比如this.$EventCalendar.toDate。
> 1、 我在实例化的页面mounted异步获取数据，拼接数据赋值到demoEvents，绑定到:events，**全部显示事件**  。
> 2、 用created异步获取，用mounted调用this.$EventCalendar.toDate(this.curday)。**显示全部事件**。
> 3、 把数据复制粘到demoEvents，**显示当天**（没意义....）。

**Comment by GeoffZhu** [comment]
那你检查一下为什么events的数据没出来就执行了toDate方法，会不会是你异步处理的有问题？我这边试了下，即便是异步拿events，toDate也是可以正常工作的
```
this.$fetch(resp => {
  this.events = resp.events
  this.$EventCalendar.toDate(this.curday)
})
```

**Comment by slimeball** [comment]
我尝试一下，谢谢
