### ISSUE TITLE
Event list not scrollabile

### ISSUE THREAD

**Issue by kalidiagne** [GeoffZhu/vue-event-calendar#37]
Events are not scrollabile in the event block, i have 9 events and i can only see 7 of it.
I added a *overflow-x: scroll;* temporally to resolve that.

**Comment by GeoffZhu** [comment]
I will fix it this weekend

**Comment by GeoffZhu** [comment]
fixed

**Comment by GeoffZhu** [comment]
Base on the design, Scrolling is the simplest solution for so many events, but scrollBar is ugly.

I try to restyle scrollbar, but some browser not supply it. 

Finally, In chrome, safari, scrollBar like this￼
![img](https://user-images.githubusercontent.com/10768286/28523382-be4666c8-70ae-11e7-9882-857ad2105fd7.jpeg)

other browser still ugly, said.
