### ISSUE TITLE
Avoid handleDayChanged event by cliking on .item without a day number

### ISSUE THREAD

**Issue by peluprvi** [GeoffZhu/vue-event-calendar#39]
#### Bug, feature request, or proposal:
`.item` without a visible day number are triggering the `handleDayChanged` method/event.

#### Steps to reproduce:
1.  Go to the [demo page](http://geoffzhu.cn/vue-event-calendar/)
2. Select a month that not start on sunday (like July 2017 or August 2017)
3. Open the console (F12)
4. Click on a blank `.item` bellow the week name

**Comment by GeoffZhu** [comment]
fixed @peluprvi

**Comment by peluprvi** [comment]
Thanks @GeoffZhu ! Remember to run the `npm update` to apply this change on demo.
