### ISSUE TITLE
add spain calendar

### ISSUE THREAD

**Issue by davidoween** [GeoffZhu/vue-event-calendar#4]
How could I add the calendar in Spanish?
The week starts on Monday, not Sunday

**Comment by GeoffZhu** [comment]
@davidoween I add some code for resolve this issues, see this [https://github.com/GeoffZhu/vue-event-calendar/commit/0379ee06a6af6def5b5dae5177e180cf0a6816a2](commit). Meybe it's not a strong way to resolve all Language， but for you , It's enough
