### ISSUE TITLE
2 29ths in October 2017

### ISSUE THREAD

**Issue by mhgbrown** [GeoffZhu/vue-event-calendar#44]
You can see this by going to the [live demo page](http://geoffzhu.cn/vue-event-calendar/) and clicking to October
<img width="514" alt="screen shot 2017-08-14 at 16 43 58" src="https://user-images.githubusercontent.com/194112/29276748-e0750b3e-810f-11e7-87d4-7287abf68141.png">

**Comment by GeoffZhu** [comment]
In my browser, It's right.
![wechatimg17](https://user-images.githubusercontent.com/10768286/29300156-5f8abf40-81a6-11e7-9cea-66c22279db6d.jpeg)

**Comment by mhgbrown** [comment]
Weird. I'm using Chrome 60. Is this somehow related to a person's locale? I'm in Germany. I haven't had a chance to dig into the code yet.

**Comment by mhgbrown** [comment]
...also occurs in Safari on iOS for me.

**Comment by GeoffZhu** [comment]
Actually, I change my Time zone， it's occurred. I will fix it at this weekend.

**Comment by Suvy-Chen** [comment]
How do I get rid of the display box next to it?

**Comment by GeoffZhu** [comment]
fixed 1.4.7
