### ISSUE TITLE
Week start on monday option

### ISSUE THREAD

**Issue by fhusquinet** [GeoffZhu/vue-event-calendar#46]
Would it be possible to add an option to choose whether the week starts on monday or not?

I would rather stick to the more modern version of the calendar which starts on monday and ends on Sunday.
I would change it myself and do a PR but I don't have enough experience with Vue Component to do so with confidence.

Thanks in advance for your anwser, and thanks for the awesome component!

**Comment by GeoffZhu** [comment]
@fhusquinet , Update to 1.4.8, and

```
Vue.use({weekStartOn: 1})
```

**Comment by fhusquinet** [comment]
Well that's just perfect, thanks a lot!
