### ISSUE TITLE
Impossible to install in vuejs ^2.1.0

### ISSUE THREAD

**Issue by Masterchoc** [GeoffZhu/vue-event-calendar#47]
Here the errors i get : 
`build.min.js:685 [Vue warn]: Error when rendering component <vue-event-calendar>: `
`build.min.js:3074 TypeError: _vm._v is not a function`

**Comment by GeoffZhu** [comment]
Vue.use(vueEventCalendar)

```
import 'vue-event-calendar/dist/style.css' 
import vueEventCalendar from 'vue-event-calendar'


Vue.use(vueEventCalendar, {locale: 'en'})
```

**Comment by Masterchoc** [comment]
This is exactly the code i used, in fact i just copy/pasted from the example.
I guess it's not working because i'm using vue 2.1.0, and your example is using the version 2.0.0.

I also tried to use it directly as a component inside a vuejs component like, but i get the same results

**Comment by GeoffZhu** [comment]
Here is the reason https://github.com/vuejs/vue-loader/issues/547,  recommend v2.1.8. :）
