### ISSUE TITLE
compile calendar- No single file component

### ISSUE THREAD

**Issue by davidoween** [GeoffZhu/vue-event-calendar#5]
I do not use single file components. I would like to insert this compiled component in my project, how to do it?

**Comment by GeoffZhu** [comment]
`<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <title>Demo</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/vue-event-calendar@1.2.14/dist/style.css">
</head>
<body>
<div id="example">
  <vue-event-calendar :events="demoEvents"></vue-event-calendar>
</div>

<script type="text/javascript" src="https://unpkg.com/vue@2.2.2/dist/vue.js"></script>
<script type="text/javascript" src="https://unpkg.com/vue-event-calendar@1.2.14/dist/index.js"></script>
<script type="text/javascript">
  Vue.use(VueEventCalendar.default, {locale: 'es', color: '#4fc08d'}) //hack in here (.default)
  new Vue({
    el: '#example',
    data: function () {
      return {
        demoEvents: [{
          date: '2016/12/15',
          title: 'Foo',
          desc: 'longlonglong description'
        },{
          date: '2016/11/12',
          title: 'Bar'
        }]
      }
    }
  })
</script>
</body>
</html>`
