### ISSUE TITLE
Default events

### ISSUE THREAD

**Issue by davidoween** [GeoffZhu/vue-event-calendar#50]
By default shows all events. How could I show my reservations today?

**Comment by GeoffZhu** [comment]
@davidoween 

```
let today = new Date()
today = `today.getFullYear()}/${today.getMonth() + 1}/${today.getDate()}`
this.$EventCalendar.toDate(today)
```

**Comment by davidoween** [comment]
I want to say where all the events are shown on the right. In other words, when loaded, all events appear on the right side by default

**Comment by GeoffZhu** [comment]
Sorry, Don't understand , what you want
