### ISSUE TITLE
Support for IE

### ISSUE THREAD

**Issue by erhansaydam** [GeoffZhu/vue-event-calendar#57]
Hi,

Can you make a refinement for the calendar to run with Internet Explorer 11. It pushes the error "Object doesn't support property or method 'assign'". I don't know it's arising from ES 6 however I am using babel-cli but that does not correct it.

Best regards.

**Comment by GeoffZhu** [comment]
Did you import 'babel-polyfill' or other 'Object. assign polyfill' @erhansaydam

**Comment by erhansaydam** [comment]
You're right, I missed to install it. But before seeing your advice, I have solved it with the polyfill explained in https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/Object/assign.

Thanks...
