### ISSUE TITLE
在线示例的bug

### ISSUE THREAD

**Issue by kevinzhou1990** [GeoffZhu/vue-event-calendar#6]
在线的示例中没有报错，但是日历无法选择日期，请看一下

**Comment by GeoffZhu** [comment]
我这里是可以选择日期的，你可以把日历翻到2016/12/15， 是可以 点击的 @kevinzhou1990

**Comment by kevinzhou1990** [comment]
@GeoffZhu 额。。只有这一个日子是可以点击的哇。。。

**Comment by GeoffZhu** [comment]
在栗子中，我只设置了两个日期 15/12/2016，12/11/2016，，因为写这个组件的时候是2016/11 ，就标在了那个时候 @kevinzhou1990

**Comment by kevinzhou1990** [comment]
@GeoffZhu 我在读源码的过程中，发现index.js中的第五行，options设置为空对象了，可是我这边本地输出的options的local总是会有个es的值，找了半天也没找出来在上面地方设置的。。

**Comment by chenxiaoxi** [comment]
能否获取所当前item类 dom节点，循环给节点添加click事件呢？

**Comment by GeoffZhu** [comment]
@chenxiaoxi  你可以通过这个(.cal-events)获取所有item的父容器, 然后通过事件代理来做

但是这样做并不好，如果要添加click事件，你可以通过自定义item来做，也就是文档中`自定义事件模版`这部分
