### ISSUE TITLE
Two of the same date (Nov 5th)

### ISSUE THREAD

**Issue by krsyoung** [GeoffZhu/vue-event-calendar#66]
Wondering if there is something up with Daylight Saving Time?  If I look at the demo page I seem to have two Nov 5th!

http://geoffzhu.cn/vue-event-calendar/

<img width="513" alt="screen shot 2017-11-05 at 10 23 26 pm" src="https://user-images.githubusercontent.com/5449541/32424040-00014310-c278-11e7-9b46-3c7bbc56f857.png">

Will dig into it but curious if others are seeing the same behaviour.

**Comment by krsyoung** [comment]
Looks like this should have been fixed by https://github.com/GeoffZhu/vue-event-calendar/pull/45.

Similar (same) issue here? https://github.com/GeoffZhu/vue-event-calendar/issues/44

**Comment by GeoffZhu** [comment]
I will update the demo page quickly.
