### ISSUE TITLE
选中切换月份bug及日期固定生成42个问题

### ISSUE THREAD

**Issue by tkggusraqk** [GeoffZhu/vue-event-calendar#68]
[选中一个事件后，切换月份，会在当月的空白日期显示选中状态，多余的空白日期行没有删除，我fork了下，进行了修复和调整。](https://github.com/tkggusraqk/vue-event-calendar)

**Comment by GeoffZhu** [comment]
为什么我看不懂你在说什么？我的日历能生成42个问题？

**Comment by tkggusraqk** [comment]
你选个日程日期，比如 这个月1号，前一个月1号是空白或者后一个月的1号是空白，你看看选中状态

**Comment by tkggusraqk** [comment]
@GeoffZhu

**Comment by GeoffZhu** [comment]
选中的还是这个月的1号啊
