### ISSUE TITLE
Order of displayed date - format

### ISSUE THREAD

**Issue by jmoore3** [GeoffZhu/vue-event-calendar#69]
I am trying to reformat the listed dates in the following fashion: MM/DD/YYYY but I cannot find where in the source code the original format of DD/MM/YYYY is. I know it's a simple issue but if you could point me in the right direction that would be awesome.

**Comment by GeoffZhu** [comment]
in File [i18n.js](https://github.com/GeoffZhu/vue-event-calendar/blob/master/src/i18n.js)
