### ISSUE TITLE
How to hide events-wrapper?

### ISSUE THREAD

**Issue by abhay7030** [GeoffZhu/vue-event-calendar#70]
Is there anyway to hide the events-wrapper

**Comment by GeoffZhu** [comment]
Use css, ```.events-wrapper{ dispaly: none; }```

**Comment by abhay7030** [comment]
Thanks for fast reply.
    <style scoped>
      .events-wrapper{ dispaly: none; }
    </style>

It is not working as expected.

**Comment by abhay7030** [comment]
@GeoffZhu
