### ISSUE TITLE
hide the .events-wrapper in only one component

### ISSUE THREAD

**Issue by abhay7030** [GeoffZhu/vue-event-calendar#71]
#70 Thanks for fast reply 
@GeoffZhu Thanks for fast reply.
`<style scoped> .events-wrapper{ dispaly: none; } </style>`

It is not working as expected.

**Comment by GeoffZhu** [comment]
<style> .events-wrapper{ dispaly: none; } </style>

**Comment by abhay7030** [comment]
I am sorry but there is only one doubt. What if I want to hide the .events-wrapper in only one component?

**Comment by abhay7030** [comment]
@GeoffZhu I am in a bit project and urgently want to know if there is any way to hide the .events-wrapper in one component only?

**Comment by Jesean** [comment]
you can enter `.events-wrapper{ dispaly: none; };` in the file named vue-event-calendar/dist/style.css

**Comment by Jesean** [comment]
you can enter `.events-wrapper{ dispaly: none; }` in the file named vue-event-calendar/dist/style.css

**Comment by abhay7030** [comment]
What if I have to show events-wrapper in one component and show in another one? I tried everything from using !important in css also.

**Comment by GeoffZhu** [comment]
```
<div class="hidden-calendar-wrapper">
  <vue-event-calendar></vue-event-calendar>
<div>

.hidden-calendar-wrapper .events-wrapper{ dispaly: none; }
```

:)
