### ISSUE TITLE
Days are shifted by weekStartOn if month starts with same weekday as weekStartOn

### ISSUE THREAD

**Issue by simonschroder** [GeoffZhu/vue-event-calendar#79]
Hi, great calendar component, thank you very much! My only problem is that the weekdays are shifted if the month starts with the same weekday as the one specified by weekStartOn. More precise, the weekdays are shifted by the value of weekStartOn. That's why the result is correct if weekStartOn is 0.
Example (weekStartOn set to 1):
![capture](https://user-images.githubusercontent.com/20194975/34439569-2d114e0c-ecaf-11e7-9eb4-ad2e5b76add2.PNG)
(The first day of 2018 is a Monday.)
It looks like the issue is the else-if in line 73 of cal-panel.vue (`} else if (this.calendar.options.weekStartOn < dayOfWeek) {`) which should be an else instead.
It would be great if you could take a look at it. Thank you!

**Comment by GeoffZhu** [comment]
fixed at 1.5.2
