### ISSUE TITLE
Errors with Vue 2.5.7

### ISSUE THREAD

**Issue by mihavidakovic** [GeoffZhu/vue-event-calendar#81]
Hey, 

I implemented everything as stated in docs, but I get these errors:
[Image](https://puu.sh/yWwwj/50e2d9b34e.png)

The calendar shows, the events loads up, but they aren't on the calendar itself.

**Comment by GeoffZhu** [comment]
Maybe something wrong in your events props.
![image](https://user-images.githubusercontent.com/10768286/34656960-376e9b52-f45c-11e7-811a-39e4a8ec90b7.png)

Can you show your code here?
