### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by a858742487** [GeoffZhu/vue-event-calendar#84]
我下载项目,然后进行npm run build打包 发现没有index.html这个文件
我用插件把index.html生成,但是发现打开是空白页.

**Comment by GeoffZhu** [comment]
我的打包配置是针对插件的，把vue组件打包成js，所以不会生成HTML。
如果你想要生成HTML，可以修改打包配置，引入html-webpack-plugin，但这样对于一个vue插件来说，并没有实际意义。 @a858742487
