### ISSUE TITLE
How i can add new even clicking on date or specifying date and time 

### ISSUE THREAD

**Issue by rajjanorkar** [GeoffZhu/vue-event-calendar#86]
Hi Team 

This is really nice calendar i have ever seen in vue js. Just would like to know how do i add new calendar events?

**Comment by rajjanorkar** [comment]
@GeoffZhu I guess it is feature request ?

**Comment by GeoffZhu** [comment]
I wrote a demo for this issue,  is this you need?
[https://jsfiddle.net/k5nftc07/22/](https://jsfiddle.net/k5nftc07/22/)

**Comment by rajjanorkar** [comment]
Hi @GeoffZhu  thank you yes it is feature request. 
i checked your demo, yes something like that in modal to add new event.
