### ISSUE TITLE
Change format for calendar heading

### ISSUE THREAD

**Issue by lalitbansal457** [GeoffZhu/vue-event-calendar#87]
Hey,

can I change the format of calendar heading, currently it is showing like 
![screenshot](https://user-images.githubusercontent.com/25577457/37143551-7c088562-22e1-11e8-8ea9-eff966ae573e.png)

 # and the desired format is

![screenshot 1](https://user-images.githubusercontent.com/25577457/37143579-953d842e-22e1-11e8-9c66-d0e34bb43e21.png)

**Comment by GeoffZhu** [comment]
Heading title format was in [this file](https://github.com/GeoffZhu/vue-event-calendar/blob/master/src/i18n.js)

![image](https://user-images.githubusercontent.com/10768286/37194970-d359a22c-23ab-11e8-8fed-1ac190c48571.png)

fork this project, and change i18n.js, rebuild, done
