### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by lalitbansal457** [GeoffZhu/vue-event-calendar#88]
npm run dev is throwing error

No configuration file found and no entry configured via CLI option.
When using the CLI you need to provide at least two arguments: entry and output.
A configuration file could be named 'webpack.config.js' in the current directory

**Comment by GeoffZhu** [comment]
Which directory does your command execute? This project root dir has 'webpack.config.js' file.

I retry `npm run dev` , it's ok
