### ISSUE TITLE
How to Change Calendar Title Format ('MM/YYYY')

### ISSUE THREAD

**Issue by naseefpv** [GeoffZhu/vue-event-calendar#93]
Hi,
First of all thank you for this beautiful calendar events component. 
I would like to know how can i change the default **calendar title format**? I'm not talking about event title.

Eg:- default format is '**MM/YYYY**' (04/2018).
I need just Month Name like 'January' or 'July'.

**Comment by GeoffZhu** [comment]
Not support yet. change source  of i18n.js for this feature.
